name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # 或者其他版本，根据你的项目需要
          distribution: 'adopt'

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease # 或者其他构建命令，根据你项目的需求

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-apk
          path: app/build/outputs/apk/release/app-release.apk # 根据你的 APK 输出路径调整
